"""Demo data used by the HR module startup seed."""

HR_TAG_SEEDS = [
    {"name": "远程协作", "category": "working_style", "description": "适应远程与混合办公节奏"},
    {"name": "文档驱动", "category": "collaboration", "description": "习惯通过文档沉淀流程与信息"},
    {"name": "会议纪要", "category": "collaboration", "description": "擅长整理会议纪要与行动项"},
    {"name": "跨部门协作", "category": "collaboration", "description": "能高效连接上下游团队推进事项"},
    {"name": "新人导师", "category": "team_role", "description": "愿意承担新人带教与融入支持"},
    {"name": "活动组织", "category": "team_role", "description": "擅长组织团队活动和内部沟通"},
    {"name": "客户沟通", "category": "business", "description": "适合承担客户跟进与需求沟通"},
    {"name": "流程优化", "category": "growth", "description": "关注流程梳理与效率提升"},
]

HR_DEPARTMENT_SEEDS = [
    {"name": "技术部", "code": "TECH", "description": "负责平台研发与技术支持", "manager_employee_no": 9001},
    {"name": "市场部", "code": "MKT", "description": "负责市场活动与品牌传播", "manager_employee_no": 9003},
    {"name": "行政部", "code": "OPS", "description": "负责行政支持与办公协同", "manager_employee_no": 9005},
    {"name": "人事部", "code": "PERSONNEL", "description": "负责招聘、员工关系与组织发展", "manager_employee_no": 9006},
    {"name": "财务部", "code": "FINANCE", "description": "负责公司财务管理与资金运营", "manager_employee_no": 9008},
]

HR_EMPLOYEE_SEEDS = [
    {
        "user": {
            "user_name": "zhouhang",
            "password": "123456",
            "role_codes": ["R_DEPT_MGR"],
            "user_email": "zhouhang@example.com",
            "nick_name": "周航",
        },
        "employee": {
            "employee_no_serial": 9001,
            "name": "周航",
            "email": "zhouhang@example.com",
            "phone": "13800000001",
            "position": "技术主管",
            "status": "active",
            "department_code": "TECH",
            "tag_names": ["远程协作", "文档驱动", "新人导师"],
        },
    },
    {
        "user": {
            "user_name": "limu",
            "password": "123456",
            "role_codes": ["R_EMPLOYEE"],
            "user_email": "limu@example.com",
            "nick_name": "李沐",
        },
        "employee": {
            "employee_no_serial": 9002,
            "name": "李沐",
            "email": "limu@example.com",
            "phone": "13800000002",
            "position": "前端工程师",
            "status": "probation",
            "department_code": "TECH",
            "tag_names": ["会议纪要", "跨部门协作", "流程优化"],
        },
    },
    {
        "user": {
            "user_name": "linyan",
            "password": "123456",
            "role_codes": ["R_DEPT_MGR"],
            "user_email": "linyan@example.com",
            "nick_name": "林妍",
        },
        "employee": {
            "employee_no_serial": 9003,
            "name": "林妍",
            "email": "linyan@example.com",
            "phone": "13800000003",
            "position": "市场主管",
            "status": "active",
            "department_code": "MKT",
            "tag_names": ["跨部门协作", "活动组织", "流程优化"],
        },
    },
    {
        "user": {
            "user_name": "chenxi",
            "password": "123456",
            "role_codes": ["R_EMPLOYEE"],
            "user_email": "chenxi@example.com",
            "nick_name": "陈希",
        },
        "employee": {
            "employee_no_serial": 9004,
            "name": "陈希",
            "email": "chenxi@example.com",
            "phone": "13800000004",
            "position": "市场专员",
            "status": "active",
            "department_code": "MKT",
            "tag_names": ["会议纪要", "活动组织", "客户沟通"],
        },
    },
    {
        "user": {
            "user_name": "songyu",
            "password": "123456",
            "role_codes": ["R_DEPT_MGR"],
            "user_email": "songyu@example.com",
            "nick_name": "宋羽",
        },
        "employee": {
            "employee_no_serial": 9005,
            "name": "宋羽",
            "email": "songyu@example.com",
            "phone": "13800000005",
            "position": "行政主管",
            "status": "active",
            "department_code": "OPS",
            "tag_names": ["远程协作", "文档驱动", "会议纪要"],
        },
    },
    {
        "user": {
            "user_name": "hanmei",
            "password": "123456",
            "role_codes": ["R_HR_MANAGER", "R_DEPT_MGR"],
            "user_email": "hanmei@example.com",
            "nick_name": "韩梅",
        },
        "employee": {
            "employee_no_serial": 9006,
            "name": "韩梅",
            "email": "hanmei@example.com",
            "phone": "13800000006",
            "position": "人事主管",
            "status": "active",
            "department_code": "PERSONNEL",
            "tag_names": ["跨部门协作", "新人导师", "流程优化"],
        },
    },
    {
        "user": {
            "user_name": "liuqing",
            "password": "123456",
            "role_codes": ["R_HR_SPECIALIST"],
            "user_email": "liuqing@example.com",
            "nick_name": "柳青",
        },
        "employee": {
            "employee_no_serial": 9007,
            "name": "柳青",
            "email": "liuqing@example.com",
            "phone": "13800000007",
            "position": "人事专员",
            "status": "probation",
            "department_code": "PERSONNEL",
            "tag_names": ["会议纪要", "客户沟通", "新人导师"],
        },
    },
    {
        "user": {
            "user_name": "qinfeng",
            "password": "123456",
            "role_codes": ["R_DEPT_MGR"],
            "user_email": "qinfeng@example.com",
            "nick_name": "秦风",
        },
        "employee": {
            "employee_no_serial": 9008,
            "name": "秦风",
            "email": "qinfeng@example.com",
            "phone": "13800000008",
            "position": "财务主管",
            "status": "active",
            "department_code": "FINANCE",
            "tag_names": ["文档驱动", "流程优化", "跨部门协作"],
        },
    },
    {
        "user": {
            "user_name": "suwan",
            "password": "123456",
            "role_codes": ["R_EMPLOYEE"],
            "user_email": "suwan@example.com",
            "nick_name": "苏婉",
        },
        "employee": {
            "employee_no_serial": 9009,
            "name": "苏婉",
            "email": "suwan@example.com",
            "phone": "13800000009",
            "position": "财务专员",
            "status": "resigned",
            "department_code": "FINANCE",
            "tag_names": ["会议纪要", "文档驱动"],
        },
    },
]
